<?php
/**
 * Template name: Terms and Conditions
 */
get_template_part('header-myaccount');
?>
<div class="company-header sections">
	<div class="container">
		<div class="breadcrumbs-sec">
            <ul>
              <li><a href="#">Home</a></li>
              <li><a href="#">Terms & Conditions</a></li>
            </ul>
         </div>
         <div class="detail-heading ">
                <h4 class="detail-title"><i class="fa fa-cube"></i>Terms and Conditions</h4>
         </div>
         <div class="privacy-policy-detail-content">
                  
                                          
          <pre>1.0   AGREEMENT.  The CareerIam L.L.C., Terms and Conditions (“Terms and Conditions”), and any Attachments (as evidenced) constitute the “Master Agreement” by and between The Subscriber, End User and CareerIam, L.L.C.,  (collectively, the “Parties” or each individually a “Party”) for the services  specified upon subscribing (“Services”).  The attachments to these Terms and Conditions (“Attachments”) further describe CareerIam, L.L.C.’s services and are hereby incorporated by reference.  The Attachments may set forth additional terms and conditions for the applicable Service and any affiliated entity providing the Services.
2.0   SERVICES.
2.1   Subject to the terms and conditions of this Master Agreement (including, without limitation, Subscriber’s compliance with its obligations set forth in Section 5), CareerIam, L.L.C. shall provide Subscriber with the Services, pursuant to and in conformance with the accepted medium upon which to render the Services stated in accordance with Section 2.2 below during the Term (as defined in Section 6 below).  Subscriber understands and agrees the Services provided are subject to internet availability and therefore subject to that connection. CareerIam, L.L.C.  Unless otherwise set forth on an applicable Attachment, CAREERIAM, L.L.C. shall use commercially reasonable efforts to provide the Services identified excluding scheduled maintenance, required repair and events beyond CAREERIAM, L.L.C.’s reasonable control.     
2.2    Subscriber shall enroll to benefit from Services provided hereunder by issuing to CAREERIAM, L.L.C. one or more proposed service subscription(s) pursuant to this Master Agreement (in the form provided or approved by CAREERIAM, L.L.C.) or via a mutually agreed electronic internet entry system.  Upon CAREERIAM, L.L.C.’s acceptance of a proposed Subscribers service(s), such service(s) shall be deemed a “Subscription” hereunder and shall be deemed incorporated into this Master Agreement.  A proposed CareerIam, L.L.C., Service shall be deemed accepted upon the earlier of (a) CAREERIAM, L.L.C.’s acceptance of such service order in writing; or (b) CAREERIAM, L.L.C.’s commencement of delivery of the Service(s) set forth in such Service description.  Furthermore, in the event Subscriber cancels their Subscription prior to CAREERIAM, L.L.C. actually delivering Services, and in the event that CAREERIAM, L.L.C. incurs any charges, then Subscriber shall reimburse CAREERIAM, L.L.C. for such charges actually incurred. 

  
3.0   SUBSCRIBER’S AND END USER’S.  Subscriber shall obtain and maintain, or ensure that each all information and uploads are in compliance with this agreement, throughout the Term (including without limitation consents) as are necessary to timely permit, and shall timely permit, CAREERIAM, L.L.C., to render the services for delivery, operation and maintenance of the Service and CAREERIAM, L.L.C. Equipment (as defined in Section 4 below) as contemplated herein at Subscriber’s and any Subscriber End User’s facilities.  Subscriber shall permit CAREERIAM, L.L.C. reasonable internet access to the Subscriber and any End User at any time as needed to, configure, upgrade, maintain or remove the CAREERIAM, L.L.C Service components collocated at Subscriber’s or by End User’s.  Subscriber shall make and maintain throughout the Term all reasonable site preparations necessary to permit the maintenance and operation of the Service and any CAREERIAM, L.L.C. as specified by and that is required to provide the Services hereunder.  In addition, Subscriber will provide CAREERIAM, L.L.C. with the relevant information and details in order to render the Service. CAREERIAM, L.L.C., shall ensure that CAREERIAM, L.L.C. does not incur, any fees or expenses whatsoever in connection with Subscriber’s provision of space, power, or access as described herein, or otherwise in connection with Subscriber’s performance of its obligations pursuant to this Section 3; and any such fees or expenses charged to a Subscriber and or End User.  CAREERIAM, L.L.C. will required consents, CAREERIAM, L.L.C. shall use commercially reasonable efforts to provide the Service in accordance with the requested Service start date indicated.  CAREERIAM, L.L.C. shall provide Subscriber and End User with a [ site number*********] upon completion of enrollment of the Service.  In the event that CAREERIAM, L.L.C. is unable to install the Service in accordance with the agreed upon schedule as a result of (i) Subscriber’s (or its End User’s) failure to deliver any required materials, information, details or payment where applicable to CAREERIAM, L.L.C.; or (ii) CAREERIAM, L.L.C. not being able to obtain access as necessary for delivery of the Service, then Subscriber shall pay CAREERIAM, L.L.C. any fee that results there from,  at CAREERIAM, L.L.C.’s then prevailing rates necessary to perform the Service.  Interconnection of the Service and CAREERIAM, L.L.C. Equipment with Subscriber’s or an End User’s, as applicable, equipment will be performed by Subscriber unless otherwise agreed in writing between the Parties.  It is Subscriber’s sole responsibility to secure and maintain any and all Subscription requirements, (as defined in Attachment B), where applicable. The End User will be required to enter into a Service Contract Agreement which is separate to this Master Agreement.


3.1 RIGHT OF SERVICES.  Subscriber’s following additional terms shall apply:
(i)     System; Services.  Subscriber hereby grants to CAREERIAM, L.L.C., the non-exclusive right to inspect, maintain, relocate and remove material which is nonconforming, to the promotion of the company or public laws and morals. fiber and/or wireless communication services distribution system (the “System”) and to market, sell and provide multichannel video, data, phone and other services (“Service Offerings”) to and from the Premises.  CAREERIAM, L.L.C. will install and maintain the System at its sole cost and expense, in a good and workmanlike manner and in accordance with good technological practices and all applicable laws, rules and regulations.
(ii)    Ownership and Use.  The System will be and remains the sole personal property of CAREERIAM, L.L.C.  Subscriber will not, and will not authorize any other party to, tamper with, attach to or use any portion of the System without the prior written approval of CAREERIAM, L.L.C. 
 (iii)   Right of Services Term.  This Section 3.1 will remain in full force and effect for so long as CAREERIAM, L.L.C. provides any Service Offering to any Subscriber or End User.
(iv)    Representations and Warranties.  Subscriber represents and warrants that (a) Subscriber has the full authority to fully perform its obligations hereunder and to grant the rights granted to CAREERIAM, L.L.C. herein, (b) no party has any contractual right or any interest that conflicts with any rights granted hereunder.
4.0   SUPPORT & MAINTENANCE.  CAREERIAM, L.L.C. shall use commercially reasonable efforts to maintain the CAREERIAM, L.L.C.-provided and installed equipment, including as applicable, any cabling, cable modems, related splitters, routers or other items, (collectively, the “CAREERIAM, L.L.C. Equipment”) on CAREERIAM, L.L.C.’s side of the demarcation points used by CAREERIAM, L.L.C. to provide the Service. CAREERIAM, L.L.C. shall provide a telephone number and email address for inquiries and remote problem support for the Service.   Subscriber is responsible for all communications and interfaces with its End Users.  In no event shall CAREERIAM, L.L.C. be responsible for providing support for any network, equipment or software not provided and installed by CAREERIAM, L.L.C. under this Master Agreement or for issues or problems beyond its control.  Notwithstanding anything to the contrary in the foregoing, CAREERIAM, L.L.C. shall use commercially reasonable efforts to restore any cable cuts on the CAREERIAM, L.L.C. network and shall keep Subscriber reasonably advised of such restoration progress. 
5.0   SUBCRIBER OBLIGATIONS.

  
5.1   Subscriber’s use of the Service (including all content transmitted via the Service) shall comply with all applicable laws and regulations and the terms of this Master Agreement.  Subscriber agrees not to resell or redistribute (whether for a fee or otherwise) the Service, or any portion thereof, or make any use of the Service other than for Subscriber’s internal business purposes, unless otherwise agreed in writing by CAREERIAM, L.L.C.  Subscriber shall ensure that its End Users’ use of the Service, if any, shall comply with all applicable laws and regulations and any applicable Terms of Use (which are incorporated herein by this reference).  “Terms of Use” means all applicable Service policies, including without limitation acceptable use policies and available on the CAREERIAM, L.L.C. web site [LIST WEBSITE], as may be modified from time to time by CAREERIAM, L.L.C., at its sole discretion.  CAREERIAM, L.L.C. may audit Subscriber’s use of the Service remotely or otherwise, to ensure Subscriber’s compliance with this Master Agreement. 
5.2   As between the Parties, Subscriber is solely responsible for (a) all use (whether or not authorized) of the Service by Subscriber, an End User or any unauthorized person or entity, which use shall be deemed Subscriber’s use for purposes of this Master Agreement; (b) all content that is viewed, stored or transmitted via the Service, as applicable; and (c) all third party charges incurred for merchandise and services accessed via the Service, if any.  Subscriber agrees to conform its equipment and software, and to ensure that each End User conforms its equipment and software, to the technical specifications for the Service provided by CAREERIAM, L.L.C. from time to time in order to attain the end objective. 
6.0   TERM.  This Master Agreement shall commence on the date of full execution by the Parties (the “Effective Date”) and shall remain in effect for the initial term set forth on the Subscription accompanying this Master Agreement (such term, the “Initial Term”, and such Order, the “Initial Order”).  Unless terminated earlier in accordance with the terms hereof, upon the expiration of the Initial Term this Master Agreement shall automatically renew on an annual basis (each such annual period, a “Renewal Term”), unless either Party provides written notice via internet of nonrenewal to the other Party at least ninety (90) days prior to the expiration of the then-current Initial Term or Renewal Term, as applicable for the End User.  The Subscriber for services is on a month-to-month basis, then this Master Agreement will continue on a month-to-month basis with respect to such Service, unless either Party provides notice of nonrenewal to the other Party at least fifteen (15) days prior to the end of the then-current month and subject to the termination rights of CAREERIAM, L.L.C. and Subscriber under this Master Agreement. The term of effectiveness of this Master Agreement shall constitute the “Term”.


7.0   PAYMENT, DEPOSITS and ADVANCE PAYMENT.  For the Service, End User agrees to pay CAREERIAM, L.L.C. all recurring and non-recurring charges, fees and taxes, (which may include activation charges, measured and usage-based charges, local, long distance, conferencing, directory assistance and operator services calling charges, where applicable) (collectively the “Service Charges”) as set forth on the Service Agreement in accordance with the following payment terms: [Service Charges will be billed to Subscriber on a monthly basis, and are payable within thirty (30) days after the date appearing on the invoice.  CAREERIAM, L.L.C. will not defer any charges while Subscriber awaits reimbursement, subsidy, discount or credit from any third party or government entity, and Subscriber shall have the obligation to pay all charges regardless of the status of any such reimbursement, subsidy, discount or credit.  CAREERIAM, L.L.C. shall have the right to increase Service Charges for each Service after the initial Order Term for such Service upon thirty (30) days written notice to Subscriber.  CAREERIAM, L.L.C. may charge a late fee for any amounts which are not paid when due.  The late fee will be the greater of i) five dollars ($5) or ii) the lesser of one and one-half percent (1.5%) per month or the highest rate chargeable by law.  Subscriber shall also be responsible for all costs of collection (including reasonable attorneys' fees) to collect overdue amounts. If CAREERIAM, L.L.C. fails to present a charge in a timely manner, such failure shall not constitute a waiver of the charges for the fees to which it relates and Subscriber shall pay such invoice in accordance with these payment terms.  If CAREERIAM, L.L.C. fails to present an invoice in a timely manner, such failure shall not constitute a waiver of the charges for the fees to which it relates and Subscriber shall pay such invoice as required by agreed upon payment terms. Subscriber may not dispute service charges or request credits more than 90-days from the payment date on invoice for such Service.]
VIEW ABOVE>>>>>
7.1   To safeguard its interests, CAREERIAM, L.L.C. may at any time verify the End User’s credit standing.  Additionally, CAREERIAM, L.L.C. may at any time require the End User to make a deposit and/or advance payment. The deposit requested will be in cash, the equivalent of cash, or a bank, credit card or account debit authorization and does not relieve the End User of the responsibility for the prompt payment of invoices on presentation. CAREERIAM, L.L.C. may deduct amounts from the deposit, bill any bank or credit card provided, or utilize any other means of payment available to CAREERIAM, L.L.C., for past due amounts payable by Subscriber to CAREERIAM, L.L.C. Upon discontinuance of Service, CAREERIAM, L.L.C. shall promptly and automatically refund the Subscriber’s deposit plus accrued interest, or the balance, if any, in excess of the unpaid bills including any penalties or termination charges assessed for Service furnished by CAREERIAM, L.L.C.
7.2   Each party is solely and exclusively responsible for ensuring performance under this Master Agreement.
8.0   TAXES.  Each Party is responsible and shall pay all federal, state, and local taxes, fees, charges, surcharges or similar exactions imposed on the Services and/or products that are the subject of this Master Agreement including but not limited to state and local sales and use taxes, telecommunications taxes, federal and state universal service fund fees and/or state and local regulatory fees to the extent applicable.  Further, CAREERIAM, L.L.C. shall have the right to recover from End User the amount of any state or local fees or taxes arising as a result of this Master Agreement, which are imposed on CAREERIAM, L.L.C. or CAREERIAM, L.L.C.’s services, or measured on CAREERIAM, L.L.C.’s receipts.  Such fees or taxes shall be invoiced to End User in the form of a surcharge included on Subscriber’s invoice.  CAREERIAM, L.L.C. shall be responsible for and shall pay all taxes measured by CAREERIAM, L.L.C.’s net income.  To the extent that a dispute arises as to which Party is liable for fees or taxes under this Master Agreement, End User shall bear the burden of proof in showing that the fee or tax is imposed upon CAREERIAM, L.L.C.’s net income.  This burden may be satisfied by End User producing written documentation from the jurisdiction imposing the fee or tax indicating that the fee or tax is based on CAREERIAM, L.L.C.’s net income.  End User shall be responsible for providing CAREERIAM, L.L.C. any and all documentation substantiating a claim for exemption from taxes or fees prior to the date that Services are first provided under this Master Agreement.  To the extent such documentation is held invalid for any reason, End User agrees to reimburse CAREERIAM, L.L.C. for any tax or fee liability including without limitation related interest and penalties arising from such invalid documentation. 
8.1   End User acknowledges that currently, and from time to time, there is uncertainty about the regulatory classification of some of the Services CAREERIAM, L.L.C. provides and, consequently, uncertainty about what fees, taxes and surcharges are due from CAREERIAM, L.L.C. and/or its affiliates.  End User agrees that CAREERIAM, L.L.C. has the right to determine, in its sole discretion, what fees, taxes and surcharges are due and to collect and remit them to the relevant governmental authorities, and/or to pay and pass them through to the End User.  End User hereby waives any claims it may have regarding CAREERIAM, L.L.C.’s collection or remittance of such fees, taxes and surcharges.  Subscriber understands that it may obtain a list of the fees, taxes and surcharges that CAREERIAM, L.L.C. currently collects or passes through by writing to CAREERIAM, L.L.C.
9.0   PROPRIETARY RIGHTS AND CONFIDENTIALITY.  (a)  CAREERIAM, L.L.C.’s Proprietary Rights.  All materials including, but not limited to, any CAREERIAM, L.L.C. Equipment (including related firmware), software, data and information provided by CAREERIAM, L.L.C., any identifiers or passwords used to access the Service or otherwise provided by CAREERIAM, L.L.C., and any know-how, methodologies or processes including, but not limited to, all copyrights, trademarks, patents, trade secrets, any other proprietary rights inherent therein and appurtenant thereto, used by CAREERIAM, L.L.C. to provide the Service (collectively “CAREERIAM, L.L.C. Materials”) shall remain the sole and exclusive property of CAREERIAM, L.L.C. or its suppliers.  Subscriber shall acquire no interest in the CAREERIAM, L.L.C. Materials by virtue of the payments provided for herein.  Subscriber and End Users may use the CAREERIAM, L.L.C. Materials solely for Subscriber’s and End User’s use of the Service.  Neither or either may disassemble, decompile, reverse engineer, reproduce, modify or distribute the CAREERIAM, L.L.C. Materials, in whole or in part, or use them for the benefit of any third party.  All rights in the CAREERIAM, L.L.C. Materials not expressly granted to Subscriber and End User herein are reserved to CAREERIAM, L.L.C.  (b) Confidentiality.  Subscriber agrees to maintain in confidence, and not to disclose to third parties or use, except for such use as is expressly permitted herein, the CAREERIAM, L.L.C. Materials and any other information and materials provided by CAREERIAM, L.L.C. in connection with this Master Agreement, including but not limited to the content of this Master Agreement, that are identified or marked as confidential or are otherwise reasonably understood to be confidential, including but not limited to the contents of this Master Agreement and any Service(s).  (c) Software.  If software is provided to Subscriber or End User hereunder (“Software”), CAREERIAM, L.L.C. grants Subscriber  and End User a limited, non-exclusive and non-transferable license to use such Software, in object code form only, solely for the purpose of using the Service for Subscriber’s employment purposes and End Users internal business purposes during the Term.  Both agree not to reverse engineer, decompile, disassemble, translate, or attempt to learn the source code of any Software related to the Services.


10.0 MONITORING, EQUIPMENT UPGRADES AND MODIFICATIONS.  CAREERIAM, L.L.C. has the right, but not the obligation, to upgrade, modify and enhance the CAREERIAM, L.L.C. network (including CAREERIAM, L.L.C. Equipment and related firmware) and the Service and take any action that CAREERIAM, L.L.C. deems appropriate to protect the Service and its facilities.  CAREERIAM, L.L.C. will notify Subscriber of any material adverse change to these Terms and Conditions (including the Terms of Use) or Service descriptions by posting such modified Terms and Conditions (including the Terms of Use) or Service description on the CAREERIAM, L.L.C. web site or by email.   If CAREERIAM, L.L.C. modifies the Services or these Terms and Conditions (including the Terms of Use) and such modification has a material adverse impact on Subscriber’s and End User’s ability to use the Service, Subscriber may terminate as specified above, and the End User within the thirty (30) day period following the date of such modification, terminate, without penalty, relating to the affected Service.
11.0 TERMINATION.  The End User or CareerIam, L.L.C. may terminate an applicable Service (a) upon thirty (30) days written notice of the other Party’s material breach, provided that such material breach is not cured within such thirty (30) day period, or (b) immediately, in the event that the other Party liquidates, is adjudicated as bankrupt, makes an assignment for the benefit of creditors, invokes any provision of law for general relief from its debtors, initiates any proceeding seeking general protection from its creditors, is removed or delisted from a trading exchange or its long term debt is downgraded more than two levels from its rating as of the Effective Date.  In addition, in the event that Subscriber  or End User fails to comply with any applicable laws or regulations, the terms of this Master Agreement or the Terms of Use, CAREERIAM, L.L.C. may upon thirty (30) days written notice suspend or discontinue any applicable Service in whole or in part without further notice, provided that such failure is not cured within such thirty (30) day period.  In addition, CAREERIAM, L.L.C. may immediately suspend Subscriber’s or its End User’s use of the Service if such use is determined by CAREERIAM, L.L.C., at its sole discretion, to be resulting in a material degradation of the CAREERIAM, L.L.C. network, until such time as such degradation has been remedied.  CAREERIAM, L.L.C. will use commercially reasonable efforts to assist the  Subscriber and End User in remedying such degradation.  In the event of a suspension, CAREERIAM, L.L.C. may require the payment of reconnect or other charges before restarting the suspended Service.  Upon the termination or expiration of this Master Agreement and the Service(s) hereunder: (i) CAREERIAM, L.L.C.’s obligations hereunder shall cease; (ii) End User promptly shall pay all amounts due and owing to CAREERIAM, L.L.C. for Service delivered prior to the date of termination or expiration, if any.
11.1 END USER EARLY TERMINATION.  Notwithstanding anything to the contrary herein, upon early termination of a Service by End User for any reason, other than as set forth in Section 11(a) or 11(b) above, or by CAREERIAM, L.L.C. for any reason set forth in Section 11(a) or 11(b) above, End User shall, at CAREERIAM, L.L.C.’s discretion promptly pay 

CAREERIAM, L.L.C. an early termination fee equal in the amount of:
(i)     $100 for early termination of placement services.
(ii)    $250 for early termination of monthly services.
(iii)   $500 for cancellation of annual services.
11.2 Additionally, in the event Subscriber terminates a portion of the Services ordered hereunder, CAREERIAM, L.L.C. may increase the rates for any remaining Services effective upon notice to Subscriber. 
11.3 The foregoing in Sections 11.1 and 11.2 shall be in addition to any other rights and remedies that CAREERIAM, L.L.C. may have under this Master Agreement or at law or equity
11.4 PORTABILITY.  End User may, upon written notice to CAREERIAM, L.L.C., discontinue or terminate Service, prior to the end of the Service Term, without payment of the applicable early termination charge set forth in Section 11.1, if:  (i) Subscriber replaces the affected Service at a new location, so long as the value of the replacement Service is equal to or greater than the Service being replaced, and (ii) Subscriber pays all non-recurring charges applicable to the replacement Service (including, without limitation, all construction expenses); and (iii) Subscriber pays any applicable third party termination liability applicable to the Service being terminated.
12.0 INDEMNIFICATION.  Subscriber and End User agree to defend, indemnify and hold harmless CAREERIAM, L.L.C., its affiliates, its service providers and suppliers and their respective officers, directors, employees and agents, from and against all liabilities, losses, costs, damages and expenses, including reasonable attorneys’ and other professionals’ fees, arising out of any third party claim arising out of or relating to (a) the use of the Service, including but not limited to a breach of Section 5 herein; or (b) personal injury or death or property damage from any cause, including but not limited to claims by Subscriber’s employees, agents, tenants or invitees, arising out of this Master Agreement, to the extent of the negligence or willful misconduct of Subscriber or its employees, agents, tenants or invitees, (c) any fees, fines or penalties incurred by CAREERIAM, L.L.C. as a result of Subscriber’s violation of the 10% Rule as set forth in Attachment D; or (d) breach of the terms governing any use of music services provided as part of the Service. 
13.0 DISCLAIMER OF WARRANTY.  SUBCRIBER AND END USER ASSUMES TOTAL RESPONSIBILITY FOR USE OF THE SERVICE AND USES THE SAME AT ITS OWN RISK.  CAREERIAM, L.L.C. EXERCISES NO CONTROL OVER AND HAS NO RESPONSIBILITY WHATSOEVER FOR THE CONTENT TRANSMITTED OR ACCESSIBLE THROUGH THE SERVICE AND CAREERIAM, L.L.C. EXPRESSLY DISCLAIMS ANY RESPONSIBILITY FOR SUCH CONTENT.  EXCEPT AS SPECIFICALLY SET FORTH IN THIS AGREEMENT, THE SERVICE, CAREERIAM, L.L.C. EQUIPMENT AND CAREERIAM, L.L.C. MATERIALS ARE PROVIDED “AS IS,” WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF TITLE, NON-INFRINGEMENT, SYSTEM INTEGRATION, DATA ACCURACY, QUIET ENJOYMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.  NO ADVICE OR INFORMATION GIVEN BY CAREERIAM, L.L.C., ITS AFFILIATES OR ITS CONTRACTORS OR THEIR RESPECTIVE EMPLOYEES SHALL CREATE ANY WARRANTY.  CAREERIAM, L.L.C. DOES NOT REPRESENT OR WARRANT THAT THE SERVICE WILL MEET SUBCRIBER’S AND END USER’S REQUIREMENTS, PREVENT UNAUTHORIZED ACCESS BY THIRD PARTIES, WILL BE UNINTERRUPTED, SECURE, ERROR FREE, WITHOUT DEGRADATION OF VOICE QUALITY OR LOSS OF CONTENT, DATA OR INFORMATION OR THAT ANY MINIMUM TRANSMISSION SPEED IS GUARANTEED AT ANY TIME.  EXCEPT AS SET FORTH IN THE MASTER AGREEMENT, CAREERIAM, L.L.C. DOES NOT WARRANT THAT ANY SERVICE OR EQUIPMENT PROVIDED BY CAREERIAM, L.L.C. WILL PERFORM AT A PARTICULAR SPEED, BANDWIDTH OR THROUGHPUT RATE.  IN ADDITION, SUBCRIBER ACKNOWLEDGES AND AGREES THAT TRANSMISSIONS OVER THE SERVICE MAY NOT BE SECURE. PARTIES FURTHER ACKNOWLEDGES AND AGREES THAT ANY DATA, MATERIAL OR TRAFFIC  OF ANY KIND WHATSOEVER CARRIED, UPLOADED, DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DONE AT SUBCRIBER’S AND END USER’S OWN DISCRETION AND RISK AND THAT EITHER OR EACH WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO SUBCRIBER’S OR AN END USER’S COMPUTER SYSTEM OR EQUIPMENT (INCLUDING NETWORK EQUIPMENT) OR LOSS OF SUCH  DATA, MATERIAL OR TRAFFIC DURING, OR THAT RESULTS FROM, SUBCRIBER’S OR ITS END USERS USE OF THE SERVICE INCLUDING, BUT NOT LIMITED TO SUBCRIBER’S OR END USER’S SENDING OR RECEIVING, OR UPLOADING OR DOWNLOADING, OR ATTEMPTS TO DO SAME, OF SUCH DATA, MATERIAL OR TRAFFIC.  IN ADDITION, SUBCRIBER ACKNOWLEDGES AND AGREES THAT CAREERIAM, L.L.C.’S THIRD PARTY SERVICE PROVIDERS DO NOT MAKE ANY WARRANTIES TO SUBCRIBER UNDER THIS AGREEMENT AND CAREERIAM, L.L.C. DOES NOT MAKE ANY WARRANTIES ON BEHALF OF SUCH SERVICE PROVIDERS UNDER THIS AGREEMENT, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, SYSTEM INTEGRATION, DATA ACCURACY OR QUIET ENJOYMENT.
14.0 LIMITATION OF LIABILITY.  IN NO EVENT SHALL CAREERIAM, L.L.C. BE LIABLE TO SUBCRIBER, AN END USER OR ANY THIRD PARTY FOR ANY INCIDENTAL, INDIRECT, CONSEQUENTIAL, SPECIAL OR PUNITIVE DAMAGES ARISING OUT OF OR RELATING TO THIS AGREEMENT, REGARDLESS OF WHETHER CAREERIAM, L.L.C. HAD BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.  CAREERIAM, L.L.C.’S AGGREGATE LIABILITY FOR ANY REASON AND ALL CAUSES OF ACTION ARISING OUT OF OR RELATING TO THIS AGREEMENT (INCLUDING, BUT NOT LIMITED TO, CONTRACT, TORT (INCLUDING NEGLIGENCE) AND STRICT PRODUCT LIABILITY) SHALL BE LIMITED TO THE FEES PAID OR OWED BY EITHER OR EACH UNDER THE SERVICE THAT IS THE SUBJECT MATTER OF THE CLAIM IN THE SIX (6) MONTHS PRECEDING THE DATE THE CLAIM ARISES.  IN NO EVENT SHALL CAREERIAM, L.L.C.’S AFFILIATES, THIRD PARTY SERVICE PROVIDERS OR SUPPLIERS HAVE ANY LIABILITY TO EITHER OR EACH HEREUNDER.  CAREERIAM, L.L.C. SHALL NOT BE RESPONSIBLE FOR ANY LOSSES OR DAMAGES ARISING AS A RESULT OF THE UNAVAILABILITY OF THE SERVICE, OR ANY FAILURE OR FAULT RELATING TO SUBCRIBER OR END USER PROVIDED EQUIPMENT, FACILITIES OR SERVICES.

  
15.0 DISCLOSURE OF SUBCRIBER INFORMATION.  Subscriber’s privacy interests, including Subscriber’s ability to limit disclosure of certain information to third parties, may be addressed by, among other laws, the Federal Telecommunications Act (the “Telecommunications Act”), the Federal Cable Communications Act (the “Cable Act”), the Electronic Communications Privacy Act, and, to the extent applicable, state laws and regulations.  Subscriber proprietary network connections information and personally identifiable information that may be collected, used or disclosed in accordance with applicable laws is described in the Privacy Notice provided by CAREERIAM, L.L.C. in writing, and, if applicable, in CAREERIAM, L.L.C.’s tariff, which are incorporated herein by reference.  Subscriber and End User acknowledges receipt of the Privacy Notice.  In addition to the foregoing, Subscriber hereby acknowledges and agrees that CAREERIAM, L.L.C. may disclose Subscriber’s personally identifiable information as required by law or regulation, or the American Registry for Internet Numbers (“ARIN”) or any similar agency, or in accordance with CAREERIAM, L.L.C.’s Privacy Notice. In addition, CAREERIAM, L.L.C. shall have the right (except where prohibited by law notwithstanding Subscriber’s consent), but not the obligation, to disclose any information to protect its rights, property and/or operations, or where circumstances suggest that individual or public safety is in peril. 
16.0 FORCE MAJEURE.  Notwithstanding anything to the contrary contained herein, a Party shall have no liability to the other hereunder due to circumstances beyond its control, including, but not limited to, acts of God, terrorism, flood, fiber cuts, natural disaster, regulation or governmental acts, fire, power surges or outages, civil disturbance, weather, or any unauthorized access to or destruction or modification of the Service, in whole or in part (each a “Force Majeure Event”).  Notwithstanding anything to the contrary herein, either Party may terminate the affected Service(s) in its entirety and without penalty if a Force Majeure Event continues for more than ten (10) consecutive days and prevents CAREERIAM, L.L.C. from delivering the Service subject to such Order(s). 
17.0 REGULATORY AND LEGAL CHANGES.  In the event of any change in applicable law, regulation, decision, rule or order, including without limitation any new application of or increase in universal service fees or other government- or quasi-government-imposed charges that increases the costs or other terms of CAREERIAM, L.L.C.’s delivery of Service to End User in providing the Service, Parties acknowledges and agrees that CAREERIAM, L.L.C. may pass through to End User any such increased fees or costs, but only to the extent of the actual increase, provided CAREERIAM, L.L.C. notifies Subscriber at least thirty (30) days in advance of the increase.  In such case, and if such increase materially increases the fees or charges due by Subscriber hereunder for the applicable Service, End User may, within thirty (30) days after notification of such increase, terminate the affected Service without incurring termination liability, provided Subscriber notifies CAREERIAM, L.L.C. at least fifteen (15) days in advance of Subscriber’s requested termination date.  Further, in the event that CAREERIAM, L.L.C. is required to file tariffs or rate schedules with a regulatory agency or otherwise publish its rates in accordance with regulatory agency rules or policies respecting the delivery of the Service or any portion thereof, and CAREERIAM, L.L.C. is required under applicable law to apply those rates to End User’s purchase of Service.  In addition, if CAREERIAM, L.L.C. determines that offering or providing the Service, or any part thereof, has become impracticable for legal or regulatory reasons or circumstances, then CAREERIAM, L.L.C. may terminate this Master Agreement as to any or all of the Service and may terminate any affected Orders, without liability by giving Subscriber thirty (30) days prior written notice or any such notice as is required by law or regulation applicable to such determination. 
17.1 This Master Agreement, its Attachments and the Order(s) are subject to all applicable federal, state or local laws and regulations in effect in the relevant jurisdiction(s) in which CAREERIAM, L.L.C. provides the Services.  If any provision of this Master Agreement, its Attachments, or the Order(s) contravene or are in conflict with any such law or regulation, then the terms of such law or regulation shall take priority over the relevant provision of this Master Agreement, its Attachments, and/or the Order(s).  If the relevant law or regulation applies to some but not all of the Service(s) being provided hereunder, then such law or regulation will take priority over the relevant provision of this Master Agreement, its Attachments, and the Order(s) only for purposes of those Service(s) to which the law or regulation applies.  Except as explicitly stated in this Master Agreement, nothing contained in this Master Agreement shall constitute a waiver by CAREERIAM, L.L.C. of any rights under applicable laws or regulations pertaining to the installation, operation, maintenance or removal of the Services, facilities or equipment.


18.0 ENTIRE AGREEMENT.  This Master Agreement, including without limitation all Attachments that are attached hereto and incorporated herein by this reference, sets forth the entire agreement between the Parties with respect to the subject matter hereof and supersedes all previous written or oral agreements or representations between the Parties with respect to such subject matter.     
19.0 COMPLIANCE WITH LAWS.  As between the Parties, CAREERIAM, L.L.C. will obtain and maintain at its own expense all licenses, approvals and regulatory authority required by law with respect to CAREERIAM, L.L.C.’s operation and provision of the Services as contemplated herein, and Subscriber will obtain and maintain at its own expense all license, approvals and regulatory authority required by law with respect to Subscriber’s use of the Services as contemplated herein.  Unless specified otherwise in this Master Agreement, each Party will give all notices, pay all fees and comply with all laws, ordinances, rules and regulations relating to its performance obligations specified herein. 
20.0 ARBITRATION.  EXCEPT FOR CLAIMS FOR INJUNCTIVE RELIEF, AS DESCRIBED BELOW, ANY PAST, PRESENT, OR FUTURE CONTROVERSY OR CLAIM ARISING OUT OF OR RELATED TO THIS AGREEMENT SHALL BE RESOLVED BY BINDING ARBITRATION ADMINISTERED BY THE AMERICAN ARBITRATION ASSOCIATION UNDER ITS COMMERCIAL ARBITRATION RULES, INCLUDING, IF APPLICABLE, THE SUPPLEMENTARY PROCEDURES FOR THE RESOLUTION OF CONSUMER RELATED DISPUTES. CONSOLIDATED OR CLASS ACTION ARBITRATIONS SHALL NOT BE PERMITTED.  THE ARBITRATOR OF ANY DISPUTE OR CLAIM BROUGHT UNDER OR IN CONNECTION WITH THIS AGREEMENT SHALL NOT HAVE THE POWER TO AWARD INJUNCTIVE RELIEF; INJUNCTIVE RELIEF MAY BE SOUGHT SOLELY IN AN APPROPRIATE COURT OF LAW.  NO CLAIM SUBJECT TO ARBITRATION UNDER THIS AGREEMENT MAY BE COMBINED WITH A CLAIM SUBJECT TO RESOLUTION BEFORE A COURT OF LAW.  THE ARBITRABILITY OF DISPUTES SHALL BE DETERMINED BY THE ARBITRATOR.  JUDGMENT UPON AN AWARD MAY BE ENTERED IN ANY COURT HAVING COMPETENT JURISDICTION.  IF ANY PORTION OF THIS SECTION IS HELD TO BE UNENFORCEABLE, THE REMAINDER SHALL CONTINUE TO BE ENFORCEABLE.


21.0 MISCELLANEOUS.  This Master Agreement shall be governed and construed in accordance with the laws of the State of Georgia, excluding its conflicts of law principles.  In the event that any portion of this Master Agreement is held to be invalid or unenforceable, the invalid or unenforceable portion shall be construed in accordance with applicable law as nearly as possible to reflect the original intentions of the parties set forth herein and the remainder of this Master Agreement shall remain in full force and effect.  No waiver of any breach or default here under shall be deemed to be a waiver of any preceding or subsequent breach or default.  Subscriber or End User may not assign this Master Agreement without the prior written consent of CAREERIAM, L.L.C., and any assignment in violation of this Section shall be null and void.  CAREERIAM, L.L.C. may assign its rights and obligations under this Master Agreement including, without limitation, in whole or in part, to any affiliate without the prior written approval of or notice to Subscriber or End User.  Subscriber understands and agrees that, regardless of any such assignment, the rights and obligations of CAREERIAM, L.L.C. herein may accrue to, or be fulfilled by, any affiliate, as well as by CAREERIAM, L.L.C. and/or its subcontractors.  Subscriber may not issue a press release, public announcement or other public statements regarding this Master Agreement without CAREERIAM, L.L.C.’s prior written consent.  Excluding any third party claims, claims under this Master Agreement must be initiated not later than two (2) years after the claim arose.  There are no third party beneficiaries to this Master Agreement.  The Parties to this Master Agreement are independent contractors.  Any notice under this Master Agreement shall be given in writing and shall be deemed to have been given when actually received by the other Party.  Notices shall be delivered to Subscriber and CAREERIAM, L.L.C. at the respective addresses set forth above, or to such other address as is provided by one Party to the other in writing.  The provisions of Sections 3.1 shall survive the termination or expiration of this Master Agreement.  No modification of any provision of this Master Agreement shall be valid unless set forth in a written instrument signed by both Parties; provided that if the Parties execute a successor master agreement, then any Services then currently in effect shall be governed by such successor master agreement and this Master Agreement shall terminate.  This Master Agreement may be executed in counterparts, each of which shall be deemed an original and all of which together shall constitute one and the same instrument.</pre>


                                        
         </div>
          
	</div>
</div>

<?php 
get_footer('login');

?>